name: Documentation Action

on:
    push:
        branches:
            - main
            - dev

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install Graphviz
              run: sudo apt-get install graphviz
            - name: Install Java
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Build and Deploy Markbind Site
              uses: markbind/markbind-action@v2
              with:
                token: ${{ secrets.BUG_ANALYSOS }}
                rootDirectory: './documentation'
                baseUrl: '/bug_analysis_FE'
                version: 'latest'
